# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170409_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            options={
                'db_table': 'query_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueryText',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'query_text',
                'managed': False,
            },
        ),
    ]
