# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(blank=True, db_column=b'test', null=True)),
            ],
            options={
                'db_table': 'test_data',
                'managed': False,
            },
        ),
    ]
